name: Challenge Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Print Working Directory
        run: pwd

      - name: List Directory Contents
        run: ls -la

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Print Python Version
        run: python --version

      - name: Create Artifact
        run: |
          echo "# This is my python artifact" > artifact.py

      - name: Run Artifact
        run: python artifact.py

