name: ML Model Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn joblib

      - name: Verify Directory Structure
        run: |
          echo "Verifying directory structure..."
          ls -la
          ls -la ModelCleaning

      - name: Clean Data
        run: |
          cd ModelCleaning
          ls -la
          python Cleandata.py

      - name: Train and Test Model
        run: |
          cd ModelCleaning
          python train_test_dataset.py

