name: Dev Branch Workflow

on:
  push:
    branches:
      - dev

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Verify Python Version
        run: python --version

      - name: Install Pandas
        run: pip install pandas

      - name: Create Python Artifact
        run: |
          echo "import pandas as pd" > artifact.py
          echo "print('Hello from artifact.py')" >> artifact.py
          echo "print('Pandas version:', pd.__version__)" >> artifact.py

      - name: Run Python Artifact
        run: python artifact.py

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Job 2 Message
        run: echo "This is Job 2 on the dev branch"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Job 3 Message
        run: echo "This is Job 3 on the dev branch"

  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Job 4 Message
        run: echo "I am job 4 and I depend on job1 and job2"

