name: Python Setup and Package Installation

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Verify Python Version
        run: python --version

      - name: Verify Pip Version
        run: pip --version

      - name: Install Pandas
        run: pip install pandas

      - name: Verify Pandas Installation
        run: python -c "import pandas as pd; print('Pandas version:', pd.__version__)"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Job 2 Message
        run: echo "This is Job 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Job 3 Message
        run: echo "This is Job 3"

  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Job 4 Message
        run: echo "I am job 4 and I depend on job1 and job2"

