name: Tutorial Workflow with Dependencies

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Job 1 Message
        run: echo "This is Job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Job 2 Message
        run: echo "This is Job 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Job 3 Message
        run: echo "This is Job 3"

  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Print Date
        run: echo "Today's date is $(date)"

      - name: Job 4 Message
        run: echo "I am job 4 and I depend on job1 and job2"

